# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-va73onssel44e

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://crva73onssel44e.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1fdd3d4eced34633afac8de29a1fd453 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bc43ef0ef18a4360b99504621064c59b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: crva73onssel44e.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1fdd3d4eced34633afac8de29a1fd453 }}/eshoponweb/web:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-va73onssel44e'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c127906d419f4f85af54ce7c3080dcbc }}
        images: 'crva73onssel44e.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1fdd3d4eced34633afac8de29a1fd453 }}/eshoponweb/web:${{ github.sha }}'